// Pairs of easy words.
module.exports = [
  ["Cat", "Dog"],
  ["Pizza", "Burger"],
  ["Beach", "Mountain"],
  ["Superhero", "Villain"],
  ["Robot", "Alien"],
  ["Pirate", "Ninja"],
  ["Summer", "Winter"],
  ["Coffee", "Tea"],
  ["Sun", "Moon"],
  ["Castle", "Spaceship"],
  ["Dragon", "Unicorn"],
  ["Volcano", "Iceberg"],
  ["Wizard", "Knight"],
  ["Jungle", "Desert"],
  ["Clown", "Ghost"],
  ["Guitar", "Drum"],
  ["Skateboard", "Bicycle"],
  ["Rainbow", "Storm"],
  ["Treehouse", "Igloo"],
  ["Octopus", "Spider"],
  ["Campfire", "Fireworks"],
  ["Mermaid", "Astronaut"],
  ["Cactus", "Coral"],
  ["Snowman", "Scarecrow"],
  ["Vampire", "Zombie"],
  ["Race Car", "Rocket Ship"],
  ["Waterfall", "Tornado"],
  ["Penguin", "Flamingo"],
  ["Taco", "Sushi"],
];
