// Pairs of hard words.
module.exports = [
  ["Cat", "Tiger"],
  ["Sandwich", "Burger"],
  ["Beach", "Sand"],
  ["Superhero", "Supervillain"],
  ["Robot", "Cyborg"],
  ["Mummy", "Ninja"],
  ["Blizzard", "Winter"],
  ["Coffee", "Tea"],
  ["Sun", "Moon"],
  ["Dragon", "Griffin"],
  ["Volcano", "Mountain"],
  ["Fighter", "Knight"],
  ["Shark", "Dolphin"],
  ["Rainbow", "Arch"],
  ["Pigeon", "Flamingo"],
  ["Cat", "Dog"],
  ["Octopus", "Spider"],
  ["Lighthouse", "Rocket"],
  ["Castle", "Mansion"],
  ["Apple", "Orange"],
  ["Apple", "Pear"],
  ["Pear", "Avocado"],
  ["Banana", "Crescent Moon"],
  ["Strawberry", "Heart"],
  ["Watermelon", "Beach Ball"],
  ["Pineapple", "Artichoke"],
  ["Tulip", "Wine Glass"],
  ["Sunflower", "Daisy"],
  ["Rose", "Cabbage"],
  ["Oak Tree", "Broccoli"],
  ["Pine Tree", "Christmas Tree"],
  ["Palm Tree", "Feather"],
  ["Broom", "Guitar"],
  ["Violin", "Cello"],
  ["Trumpet", "Megaphone"],
  ["Maracas", "Salt Shaker"],
  ["Fork", "Rake"],
  ["Hammer", "Gavel"],
  ["Shovel", "Oar"],
  ["Broom", "Witch Hat"],
  ["Lantern", "Thermos"],
  ["Flashlight", "Candle"],
  ["Clock", "Compass"],
  ["Compass", "Radar"],
  ["Telescope", "Periscope"],
  ["Camera", "Binoculars"],
  ["Glasses", "Goggles"],
  ["Baseball Cap", "Beanie"],
  ["Backpack", "Suitcase"],
  ["Briefcase", "Lunchbox"],
  ["Book", "Tablet"],
  ["Notebook", "Calendar"],
  ["Map", "Treasure Map"],
  ["Letter", "Postcard"],
  ["Envelope", "Pillow"],
  ["Bed", "Sofa"],
  ["Chair", "Toilet"],
  ["Table", "Desk"],
  ["Lamp", "Streetlight"],
  ["Window", "Picture Frame"],
  ["Door", "Gate"],
  ["Bridge", "Rainbow"],
  ["Tunnel", "Cave"],
  ["Well", "Volcano"],
  ["Fountain", "Waterfall"],
  ["Pyramid", "Tent"],
  ["Pagoda", "Castle"],
  ["Barn", "House"],
  ["Ferris Wheel", "Carousel"],
  ["Roller Coaster", "Water Slide"],
  ["Swing", "Hammock"],
  ["Slide", "Ramp"],
  ["Skateboard", "Snowboard"],
  ["Surfboard", "Ironing Board"],
  ["Sled", "Wheelbarrow"],
  ["Sailboat", "Kite"],
  ["Submarine", "Whale"],
  ["Airplane", "Bird"],
  ["Helicopter", "Dragonfly"],
  ["Train", "Roller Coaster"],
  ["Bus", "Van"],
  ["Truck", "Tractor"],
  ["Motorcycle", "Bicycle"],
  ["Tire", "Inner Tube"],
  ["Anchor", "Hook"],
  ["Shield", "Flying Saucer"],
  ["Bow", "Slingshot"],
  ["Cane", "Walking Stick"],
  ["Snowflake", "Star"],
  ["Cloud", "Sheep"],
  ["Comet", "Firework"],
  ["Fire", "Flame"],
  ["Smoke", "Cloud"],
  ["Wave", "Snake"],
  ["River", "Road"],
  ["Sandcastle", "Castle"],
  ["Snowman", "Stack of Rocks"],
  ["Lizard", "Crocodile"],
  ["Whale", "Dolphin"],
  ["Seal", "Otter"],
  ["Bat", "Bird"],
  ["Bee", "Ladybug"],
  ["Millipede", "Caterpillar"],
  ["Snail", "Shell"],
  ["Crab", "Scorpion"],
  ["Cow", "Bull"],
  ["Goat", "Ram"],
  ["Pig", "Boar"],
  ["Chicken", "Eagle"],
  ["Owl", "Penguin"],
  ["Parrot", "Toucan"],
  ["Peacock", "Turkey"],
  ["Lion", "Tiger"],
  ["Leopard", "Cheetah"],
  ["Bear", "Gorilla"],
  ["Deer", "Moose"],
  ["Fox", "Wolf"],
  ["Rabbit", "Kangaroo"],
  ["Mouse", "Hamster"],
  ["Snake", "Eel"],
  ["Mummy", "Skeleton"],
  ["Witch", "Wizard"],
  ["Vampire", "Bat"],
  ["Werewolf", "Wolf"],
  ["Pirate", "Sailor"],
  ["Cowboy", "Ranger"],
  ["Sheriff", "Police Officer"],
  ["Doctor", "Scientist"],
  ["Chef", "Baker"],
  ["Firefighter", "Astronaut"],
  ["Diver", "Astronaut"],
  ["Clown", "Mime"],
  ["King", "Queen"],
  ["Prince", "Knight"],
  ["Angel", "Fairy"],
  ["Gnome", "Dwarf"],
  ["Football", "Rugby"],
  ["Love", "Like"],
  ["Run", "Walk"],
  ["Jump", "Hop"],
  ["Climb", "Crawl"],
  ["Throw", "Catch"],
  ["Sleep", "Dream"],
  ["Sing", "Talk"],
  ["Dance", "Skate"],
  ["Cook", "Eat"],
  ["Draw", "Write"],
  ["Tennis", "Badminton"],
  ["Baseball", "Cricket"],
  ["Hockey", "Lacrosse"],
  ["Boxing", "Wrestling"],
  ["Golf", "Croquet"],
  ["Volleyball", "Dodgeball"],
  ["Soccer", "Basketball"],
  ["Ice Skating", "Roller Skating"],
  ["Surfing", "Paddleboarding"],
  ["Archery", "Darts"],
  ["Bowling", "Curling"],
  ["Marathon", "Race"],
  ["Relay Race", "Tug of War"],
  ["Gymnastics", "Ballet"],
  ["Diving", "Synchronized Swimming"],
  ["Pancake", "Waffle"],
  ["Muffin", "Cupcake"],
  ["Cookie", "Biscuit"],
  ["Pretzel", "Croissant"],
  ["Hot Dog", "Burrito"],
  ["Taco", "Wrap"],
  ["Noodles", "Spaghetti"],
  ["Soup", "Stew"],
  ["Lemonade", "Iced Tea"],
  ["Milkshake", "Smoothie"],
  ["Jam", "Jelly"],
  ["Cheese", "Tofu"],
  ["Carrot", "Parsnip"],
  ["Corn", "Bamboo"],
  ["Lettuce", "Cabbage"],
  ["Donut", "Bagel"],
  ["Popcorn", "Cotton Candy"],
  ["Piano", "Keyboard"],
  ["Saxophone", "Clarinet"],
  ["Drum", "Tambourine"],
  ["Headphones", "Earmuffs"],
  ["Necklace", "Chain"],
  ["Ring", "Bracelet"],
  ["Scissors", "Pliers"],
  ["Screwdriver", "Chisel"],
  ["Needle", "Pin"],
  ["Bucket", "Basket"],
  ["Bottle", "Vase"],
  ["Mug", "Bowl"],
  ["Plate", "Frisbee"],
  ["Chopsticks", "Tongs"],
  ["Refrigerator", "Cabinet"],
  ["Oven", "Microwave"],
  ["Shower", "Bathtub"],
  ["Pillow", "Cushion"],
  ["Curtain", "Blanket"],
  ["Ladder", "Staircase"],
  ["Mailbox", "Birdhouse"],
  ["Traffic Light", "Stop Sign"],
  ["Street Sign", "Road Sign"],
  ["Chimney", "Tower"],
  ["Fence", "Wall"],
  ["Garage", "Warehouse"],
  ["Skyscraper", "Apartment"],
  ["Church", "Mosque"],
  ["Library", "Bookstore"],
  ["Hospital", "Hotel"],
  ["Museum", "Gallery"],
  ["Market", "Mall"],
  ["Park", "Garden"],
  ["Campsite", "Picnic Area"],
  ["Tent", "Canopy"],
  ["Coconut", "Bowling Ball"],
  ["Acorn", "Chestnut"],
  ["Pinecone", "Artichoke"],
  ["Vine", "Rope"],
  ["Kelp", "Seaweed"],
  ["Moss", "Grass"],
  ["Canyon", "Valley"],
  ["Cliff", "Mountain"],
  ["Cave", "Grotto"],
  ["Meadow", "Prairie"],
  ["Forest", "Jungle"],
  ["Oasis", "Pond"],
  ["Puddle", "Lake"],
  ["Mist", "Fog"],
  ["Hail", "Snow"],
  ["Rainbow", "Aurora"],
  ["Dawn", "Sunset"],
  ["Shadow", "Reflection"],
  ["Camel", "Llama"],
  ["Zebra", "Donkey"],
  ["Giraffe", "Ostrich"],
  ["Hippopotamus", "Rhinoceros"],
  ["Monkey", "Koala"],
  ["Squirrel", "Chipmunk"],
  ["Duck", "Goose"],
  ["Swan", "Pelican"],
  ["Squid", "Jellyfish"],
  ["Lobster", "Shrimp"],
  ["Stingray", "Manta Ray"],
  ["Salamander", "Newt"],
  ["Chameleon", "Iguana"],
  ["Gecko", "Lizard"],
  ["Hedgehog", "Porcupine"],
  ["Skunk", "Badger"],
  ["Raccoon", "Red Panda"],
  ["Donkey", "Mule"],
  ["Sheep", "Alpaca"],
  ["Rooster", "Turkey"],
  ["Hawk", "Falcon"],
  ["Robin", "Sparrow"],
  ["Crow", "Raven"],
  ["Seagull", "Albatross"],
  ["Hummingbird", "Bee"],
  ["Moth", "Butterfly"],
  ["Mosquito", "Dragonfly"],
  ["Wasp", "Hornet"],
  ["Beetle", "Cockroach"],
  ["Centipede", "Millipede"],
  ["Earthworm", "Leech"],
  ["Detective", "Spy"],
  ["Farmer", "Gardener"],
  ["Pilot", "Captain"],
  ["Teacher", "Professor"],
  ["Artist", "Painter"],
  ["Photographer", "Reporter"],
  ["Mechanic", "Engineer"],
  ["Builder", "Architect"],
  ["Mail Carrier", "Delivery Driver"],
  ["Lifeguard", "Swimmer"],
  ["Magician", "Illusionist"],
  ["Mermaid", "Siren"],
  ["Pirate", "Viking"],
  ["Elf", "Pixie"],
  ["Giant", "Troll"],
  ["Werewolf", "Bear"],
  ["Read", "Study"],
  ["Look", "Watch"],
  ["Listen", "Hear"],
  ["Hug", "Kiss"],
  ["Paint", "Color"],
  ["Build", "Construct"],
  ["Ride", "Drive"],
  ["Sail", "Row"],
  ["Fly", "Glide"],
  ["Dig", "Plant"],
  ["Pour", "Drink"],
  ["Bake", "Fry"],
  ["Kick", "Punt"],
  ["Spin", "Twirl"],
  ["Wave", "Point"],
  ["Smile", "Laugh"],
  ["Cry", "Sob"],
  ["Fear", "Worry"],
  ["Anger", "Frustration"],
  ["Dig", "Shovel"],
  ["Paint", "Brush"],
  ["Write", "Pencil"],
  ["Cut", "Scissors"],
  ["Hammer", "Nail"],
  ["Sew", "Needle"],
  ["Stir", "Spoon"],
  ["Drink", "Cup"],
  ["Pour", "Pitcher"],
  ["Sweep", "Broom"],
  ["Mop", "Bucket"],
  ["Vacuum", "Carpet"],
  ["Wash", "Soap"],
  ["Brush", "Toothbrush"],
  ["Comb", "Hairbrush"],
  ["Shave", "Razor"],
  ["Tie", "Shoelace"],
  ["Unlock", "Key"],
  ["Open", "Door"],
  ["Zip", "Jacket"],
  ["Climb", "Ladder"],
  ["Ride", "Bicycle"],
  ["Drive", "Car"],
  ["Fly", "Airplane"],
  ["Sail", "Boat"],
  ["Row", "Oar"],
  ["Shoot", "Bow"],,
  ["Ring", "Bell"],
  ["Knock", "Door"],
  ["Read", "Book"],
  ["Photograph", "Camera"],
  ["Call", "Phone"],
  ["Type", "Keyboard"],
  ["Print", "Printer"],
  ["Slice", "Sliver"],
  ["Plant", "Seed"],
  ["Pick", "Flower"],
  ["Build", "Brick"],
];
