// Pairs of medium-difficulty words.
module.exports = [
  ["Candle", "Lantern"],
  ["Bridge", "Tunnel"],
  ["Compass", "Map"],
  ["Camera", "Binoculars"],
  ["Sailboat", "Speedboat"],
  ["Feather", "Leaf"],
  ["Hourglass", "Clock"],
  ["Key", "Lock"],
  ["Mirror", "Window"],
  ["Backpack", "Suitcase"],
  ["Pillow", "Cloud"],
  ["Umbrella", "Parachute"],
  ["Anchor", "Rock"],
  ["Whistle", "Flute"],
  ["Drumstick", "Hammer"],
  ["Paintbrush", "Toothbrush"],
  ["Ladder", "Stairs"],
  ["Wheelbarrow", "Shopping Cart"],
  ["Mailbox", "Birdhouse"],
  ["Fountain", "Waterfall"],
  ["Cave", "Igloo"],
  ["Lighthouse", "Tower"],
  ["Pyramid", "Mountain"],
  ["Tent", "Treehouse"],
  ["Carousel", "Ferris Wheel"],
  ["Roller Skate", "Ice Skate"],
  ["Kite", "Balloon"],
  ["Tricycle", "Bicycle"],
  ["Canoe", "Surfboard"],
  ["Train", "Bus"],
  ["Acorn", "Pinecone"],
  ["Mushroom", "Umbrella"],
  ["Pinecone", "Pineapple"],
  ["Coconut", "Bowling Ball"],
  ["Sunflower", "Daisy"],
  ["Seashell", "Ear"],
  ["Jellyfish", "Balloon"],
  ["Crab", "Spider"],
  ["Chameleon", "Lizard"],
  ["Owl", "Eagle"],
  ["Bee", "Hummingbird"],
  ["Fox", "Wolf"],
  ["Turtle", "Helmet"],
  ["Crown", "Tiara"],
  ["Wizard", "Magician"],
  ["Detective", "Police Officer"],
  ["Astronaut", "Diver"],
  ["Chef", "Artist"],
  ["Robot", "Toy Soldier"],
  ["Treasure Chest", "Safe"],
  ["Snow Globe", "Fishbowl"],
  ["Board Game", "Puzzle"],
  ["Checkers", "Chess"],
  ["Newspaper", "Magazine"],
  ["Radio", "Television"],
  ["Typewriter", "Computer"],
  ["Teapot", "Coffee Pot"],
  ["Sandcastle", "Snow Fort"],
  ["Campfire", "Fire Pit"],
  ["Bonfire", "Fireplace"]
];
